version: v0.2.34 # Should be managed by CI, but currently matching Issue Number

---
spring:
  profiles: production
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true
#    elasticsearch:
#      cluster-nodes: 10.10.1.10:9300
  jpa:
    show-sql: false
server:
  port: ${port:80}

---
spring:
  profiles: development
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true
#    elasticsearch:
#      cluster-nodes: 192.168.30.10:9300
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true # /h2-console for h2 web interface
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:memberdb
    username: sa
    password:
server:
  port: ${port:8081}
